### ISSUE TITLE
NA value error?

### ISSUE THREAD

**Issue by JahanRahman** [BIMSBbioinfo/ikarus#11] opened 2022-06-27 16:24 UTC
Hi Jan,

Running into this error here: 
Less than 80% of the genes in Normal are present in the expression matrix.
Less than 80% of the genes in Tumor are present in the expression matrix.
/juno/work/greenbaum/users/rahmanj/vardhana_lab/rux_b_cell_single_cell_analysis/rux/lib/python3.8/site-packages/sklearn/base.py:443: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
Traceback (most recent call last):
  File "ikarus_cell_classifier.py", line 21, in <module>
    predictions = model.predict(adata, 'Impact_Rux')
  File "rux_b_cell_single_cell_analysis/rux/lib/python3.8/site-packages/ikarus/classifier.py", line 375, in predict
    y_pred = self.core_model.predict(scores)
  File "rux_b_cell_single_cell_analysis/rux/lib/python3.8/site-packages/sklearn/linear_model/_base.py", line 447, in predict
    scores = self.decision_function(X)
  File "rux_b_cell_single_cell_analysis/rux/lib/python3.8/site-packages/sklearn/linear_model/_base.py", line 429, in decision_function
    X = self._validate_data(X, accept_sparse="csr", reset=False)
  File "rux_b_cell_single_cell_analysis/rux/lib/python3.8/site-packages/sklearn/base.py", line 577, in _validate_data
    X = check_array(X, input_name="X", **check_params)
  File rux_b_cell_single_cell_analysis/rux/lib/python3.8/site-packages/sklearn/utils/validation.py", line 899, in check_array
    _assert_all_finite(
  File "rux_b_cell_single_cell_analysis/rux/lib/python3.8/site-packages/sklearn/utils/validation.py", line 146, in _assert_all_finite
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

**Comment by neil-n-zhang** [comment] 2022-07-01 19:27
Hi Jahan, it is possible that the gene names are missing in your sample, you can check sample.to_df().head(2) to see whether column names are gene names.

**Comment by jmodlis** [comment] 2022-08-17 14:29
Hello, I think I am running into this same issue.  The first warning occurs when I load the core model.

```
>>> model = classifier.Ikarus(signatures_gmt=signatures_file, out_dir="./../working/ikarus")
>>> model.load_core_model(trained_model_file)
/datastore/scripts/mamba/envs/ikarus/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator LogisticRegression from version 0.24.2 when using version 1.1.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
```
Then, there is the ValueError seen by @JahanRahman when running the predictions.  The resulting csv is an empty, comma-separated file.  I think the key here is this warning:
```
UserWarning: X has feature names, but LogisticRegression was fitted without feature names
```
I verified that my anndata object has the correct gene names as var names, so the problem is probably coming from the pre-trained model, not the input data. There are several other similar errors on the internet - referring to utilizing a pre-trained sklearn model from a different version of sklearn than that which is currently installed.  Currently I'm testing if training the model myself will resolve the issue.

**Comment by melonheader** [comment] 2022-08-19 08:38
Hello @jmodlis, could you paste the full warning message?
Your insert is cut on the last line. 
Nonetheless, if the error goes as
```
Less than 80% of the genes in Normal are present in the expression matrix.
Less than 80% of the genes in Tumor are present in the expression matrix.
```
you would need to check first if the _gene names_ in your _anndata_ actually intersect with the gene names from the signatures used in the pre-trained models. It is very rare, but it could be that the intersection is actually less than 80% of the signature genes. 
The signatures themselves one can find at `ikarus/tutorials/out/signatures.gmt`

**Comment by dohmjan** [comment] 2022-08-19 10:32
I agree with @melonheader, intersecting less than 80% of the genes might be the reason for the error. This threshold is introduced in the scoring algorithm we are using. After checking the intersection, you might try to circumvent the issue by removing non-overlapping genes from the gene set (knowing that this might decrease accuracy). For that, you could try the argument `adapt_signatures` when initializing the model object, e.g. `model = classifier.Ikarus(..., adapt_signatures=True)`. This should be available in theGitHub version of Ikarus.

**Comment by Cristinacondel1** [comment] 2022-09-20 15:36
Hi, 

I'm facing the same issue as JahanRahman:

>>> _ = model.predict(adata, "HeadNNeck", save=True)
Less than 80% of the genes in Tumor are present in the expression matrix.
Less than 80% of the genes in Normal are present in the expression matrix.
/home/c581z/.conda/envs/ikarus/lib/python3.8/site-packages/sklearn/base.py:443: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/c581z/.conda/envs/ikarus/lib/python3.8/site-packages/ikarus/classifier.py", line 375, in predict
    y_pred = self.core_model.predict(scores)
  File "/home/c581z/.conda/envs/ikarus/lib/python3.8/site-packages/sklearn/linear_model/_base.py", line 447, in predict
    scores = self.decision_function(X)
  File "/home/c581z/.conda/envs/ikarus/lib/python3.8/site-packages/sklearn/linear_model/_base.py", line 429, in decision_function
    X = self._validate_data(X, accept_sparse="csr", reset=False)
  File "/home/c581z/.conda/envs/ikarus/lib/python3.8/site-packages/sklearn/base.py", line 577, in _validate_data
    X = check_array(X, input_name="X", **check_params)
  File "/home/c581z/.conda/envs/ikarus/lib/python3.8/site-packages/sklearn/utils/validation.py", line 899, in check_array
    _assert_all_finite(
  File "/home/c581z/.conda/envs/ikarus/lib/python3.8/site-packages/sklearn/utils/validation.py", line 146, in _assert_all_finite
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

I checked that the gene names where stablished as columns which they are and then I checked for the overlapping:
-For tumor genes: 70% were found overlapping
-For normal genes: 84% were found overlapping

So then I decided to try the suggestion from @dohmjan, adding adapt_signatures = TRUE to the model, but then I get the following error:

_ = model.predict(adata, "HeadNNeck", save=True)
Traceback (most recent call last):
  File "/home/c581z/.conda/envs/ikarus/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3800, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'gene_symbol'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/c581z/.conda/envs/ikarus/lib/python3.8/site-packages/ikarus/classifier.py", line 363, in predict
    signatures_gmt = check_signatures_overlap(
  File "/home/c581z/.conda/envs/ikarus/lib/python3.8/site-packages/ikarus/classifier.py", line 158, in check_signatures_overlap
    tumor_genes_in_var = list(set(tumor_genes) & set(adata.var["gene_symbol"].values.tolist()))
  File "/home/c581z/.conda/envs/ikarus/lib/python3.8/site-packages/pandas/core/frame.py", line 3805, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/c581z/.conda/envs/ikarus/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3802, in get_loc
    raise KeyError(key) from err
KeyError: 'gene_symbol'

And I'm not too sure how to proceed now

**Comment by dohmjan** [comment] 2022-09-21 07:47
Hi! Could you check whether within your AnnData object the column containing the genes of the dataset is called "gene_symbol"? For example via `plot(adata.var.head())`, assuming your AnnData object is called `adata`. If not you would have to rename it to "gene_symbol", that would be necessary. As for that, the provided instructions are not very good. I'll try to make this more clear in the tutorial if a custom AnnData object is used that is not created via `data.load_dense()` or `data.load_sparse()`.

**Comment by Cristinacondel1** [comment] 2022-09-21 14:00
> Hi! Could you check whether within your AnnData object the column containing the genes of the dataset is called "gene_symbol"? For example via `plot(adata.var.head())`, assuming your AnnData object is called `adata`. If not you would have to rename it to "gene_symbol", that would be necessary. As for that, the provided instructions are not very good. I'll try to make this more clear in the tutorial if a custom AnnData object is used that is not created via `data.load_dense()` or `data.load_sparse()`.

This solved the problem, thanks! The data.var was not properly formatted (it was an empty data frame with gene names stored in index) but reformatting it and adding gene_symbol as column name fixed it.

**Comment by dohmjan** [comment] 2022-09-22 10:27
Great, I'd propose to close the issue. Feel free to re-open again!

**Comment by dohmjan** [comment] 2022-09-22 11:15
I'd propose to close the issue for now. Feel free to re-open it again!

**Comment by dohmjan** [comment] 2022-09-22 13:17
I'd propose to close the issue for now. Feel free to re-open again!

**Closed by dohmjan** 2022-09-22 13:17 UTC

**Comment by jpark27** [comment] 2023-11-10 03:46
Dear @dohmjan 

Hello! Thank you so much for sharing great tool/support to the community.
I come across with similar issues but so far haven't success in any of previous solutions worked on my data (e.g., scanpy pre-processing, changing adata.var_names to gene_symbol, etc). Any chance can you give instructions how to use user-specific h5ad?

![image](https://github.com/BIMSBbioinfo/ikarus/assets/59645310/607dd48e-3709-4060-9d8f-c71bb4c36714)


Currently, my anndata files are processed
(1) public scRNA-seq data from diff studies-> STARsolo pipeline -> annotated R/python tools -> merged in one anndata ->
(2) split into authors for ikarus
(3) one of dataset used to make trained-model (wen through ok)
(4) rest used for model prediction but failed with following mssg.

`
ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

#make prediction
#We provide the AnnData of an unknown data set, make predictions and save the results.

_ = model.predict(cdatas["Lin2021"], "/lustre/scratch126/cellgen/team283/jp27/02_tools/ikarus/livers/out/Lin2021", save=True)
#make prediction`

Here is one of anndata I generated and problematic..
https://drive.google.com/file/d/1-VHW4h6ofUbNZ92hg_khkF-dck15nEOX/view?usp=sharing

Any tips would be super appreciated,
Jun

**Comment by anu-bioinfo** [comment] 2024-02-07 10:15
@jpark27 
Did you try --- model = classifier.Ikarus(..., adapt_signatures=True)
Had the same error as you. The above worked for me after everything else failed.
